before_script:
  - docker info

build-test-deploy-accel:
  script:
    - docker build --pull=true -t concrete-python:accel .
    - docker run --rm concrete-python:accel bash check-style.bash
    - docker run --rm concrete-python:accel python setup.py install --user
    - docker run --rm concrete-python:accel python setup.py test
    - docker run --rm concrete-python:accel python setup.py test --addopts integration-tests
    - # work around gitlab CI... only deploy on accel
      bash -c "[[ $CI_BUILD_REF_NAME != accel ]] ||
      (docker tag concrete-python:accel r8n01:5000/concrete-python:accel &&
      docker push r8n01:5000/concrete-python:accel)"
  tags:
    - shell
